dist: trusty

sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      env:
      - COMPILERCXX="g++-5"
      - COMPILERC="gcc-5"
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5             #libstdc++5 required
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
before_script:
  - if [ -n "$COMPILERC" ]; then export CC=$COMPILERC; fi
  - if [ -n "$COMPILERCXX" ]; then export CXX=$COMPILERCXX; fi 
  - mkdir build
  - cd build
  - cmake ..

script: make -j3 && make test

notifications:
  recipients:
    - souare.saidou@gmail.com
  email:
    on_success: change
    on_failure: always
