dist: xenial

language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
      env:
      - COMPILERCXX="g++-5"
      - COMPILERC="gcc-5"
before_script:
  - if [ -n "$COMPILERC" ]; then export CC=$COMPILERC; fi
  - if [ -n "$COMPILERCXX" ]; then export CXX=$COMPILERCXX; fi
  - sudo apt-get -y install libpqxx-dev libpq-dev postgresql-server-dev-all libboost-all-dev
  - mkdir build
  - cd build
  - cmake -DBUILD_COVERAGE=ON ..

script: make -j3 && make test -j3

after_success:
  - cd ..
  - ls -la
  - pip install --user cpp-coveralls    
  - coveralls --root . --build-root build/ --gcov-options '\-lp' -e build/Testing/ -e build/restbed-src/ -e build/restbed-download/ -e build/restbed-build/ -e build/_rapidjson_deps/ -e build/_deps/ -e build/CMakeFiles/    
notifications:
  recipients:
    - souaremsaidou@gmail.com
  email:
    on_success: change
    on_failure: always
